module.exports = STATE = {
    NONE: "NONE",
    NEW: "NEW",
    UNSTRUCTURED: "UNSTRUCTURED",
    PROBLEMATIC: "PROBLEMATIC",
    PROBLEMATIC_SOLUTION: "PROBLEMATIC_SOLUTION",
    HOW_IT_WORKS: "HOW_IT_WORKS",
    TECHNOLOGY: "TECHNOLOGY",
};
